In [12]:
# import preprocess as prep
import SLR_model_GRU
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1" 
import importlib
import preprocess
# model will output multiple(15) results/sec, how are we gonna handle it?

In [21]:
importlib.reload(SLR_model_GRU)
importlib.reload(preprocess)


<module 'preprocess' from '/home/shd/BomNae-SLR/preprocess.py'>

In [22]:
# Configurations
model_dir = "saves_GRU"
THRESHOLD = 0.5
# batch_size = 16

In [23]:
# 세이브된 모델 로드
load_path = os.path.join(model_dir, "ckpt","11-06-16-50epochs-2times.keras")
model = SLR_model_GRU.load_model(load_path)

In [24]:
# load data
l_raws=[]
r_raws=[]
p_raws=[]
y_raws=[]
person_id = 1
# TODO hardcode path
# a video
for j in sorted(os.listdir(os.path.join(preprocess.getoutputdir(),str(person_id)))):
    j="0100.npz"
    l_raw, r_raw, p_raw, y_raw ,w= preprocess.load_data(f"{person_id}/{j}")
    
    l_raws.append(l_raw)
    r_raws.append(r_raw)
    p_raws.append(p_raw)
    y_raws.append(y_raw)
    break

In [25]:
y_raws

[99]

In [26]:
# # dummy x_raw data
# l_raws = []
# duration_list = []
# h_elem = np.zeros(shape=(4,5,3))
# # p_elem = np.zeros(shape=(3,10))
# # comb_elem = [h_elem, h_elem, p_elem]
# x_elem = []
# duration = (np.random.randint(90,100))
# duration_list.append(duration)
# for j in range(duration): # frame size
#     x_elem.append(h_elem)
#     # x_elem.append(comb_elem)
# l_raws.append(x_elem)
# r_raws = []
# 
# h_elem = np.zeros(shape=(4,5,3))
# # p_elem = np.zeros(shape=(3,10))
# # comb_elem = [h_elem, h_elem, p_elem]
# x_elem = []
# duration = duration_list[0]
# for j in range(duration): # frame size
#     x_elem.append(h_elem)
#     # x_elem.append(comb_elem)
# r_raws.append(x_elem)
# p_raws = []
# 
# # h_elem = np.zeros(shape=(4,5,3))
# p_elem = np.zeros(shape=(3,10))
# # comb_elem = [h_elem, h_elem, p_elem]
# x_elem = []
# duration = duration_list[0]
# for j in range(duration): # frame size
#     # x_elem.append(h_elem)
#     x_elem.append(p_elem)
#     # x_elem.append(comb_elem)
# p_raws.append(x_elem)

In [27]:
l_test, each = SLR_model_GRU.serialize(l_raws)
r_test, each = SLR_model_GRU.serialize(r_raws)
p_test, each = SLR_model_GRU.serialize(p_raws, stride=2)
x_test = (l_test, r_test, p_test)

# dataset = SLR_model.convert_to_dataset_single(x_test, batch_size)


# with open(hist_path, 'w') as file:
#     json.dump(hist.history, file)

In [28]:
x_test[1].shape

(18, 9, 4, 5, 3)

In [29]:

predictions = model.predict(x_test,32)
print(SLR_model_GRU.decode_onehot2d(predictions))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step
tf.Tensor(
[1898 1898 1898 1898 1898 1898 1898 1898 1898 2732  188 2259 2259 2259
   49 1898 1898 1898], shape=(18,), dtype=int64)


W0000 00:00:1730944718.987594    8350 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730944718.989922    8344 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730944718.990181    8350 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730944718.990783    8344 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730944718.990999    8350 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730944718.991344    8344 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730944718.991653    8350 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730944718.991949    8344 gpu_timer.cc:114] Skipping the delay kernel, measurement accuracy will be reduced
W0000 00:00:1730944718.992236    8350 gp

In [ ]:
predictions

array([[7.9010423e-16, 3.3546442e-19, 2.8880013e-28, ..., 6.2367728e-19,
        4.2299254e-18, 1.5826244e-16],
       [1.3019671e-17, 2.2345743e-21, 2.4805354e-28, ..., 7.5384776e-20,
        2.5882523e-18, 5.4566355e-18],
       [1.9817608e-20, 1.7838993e-23, 4.4732374e-32, ..., 1.6420462e-22,
        1.9081687e-20, 6.3201866e-21],
       ...,
       [4.3076135e-23, 1.4819824e-27, 1.0392310e-33, ..., 3.6207864e-27,
        5.4690183e-25, 3.4301395e-23],
       [4.0488436e-22, 5.7491828e-25, 7.4267833e-32, ..., 1.9858946e-25,
        2.9434539e-22, 5.8357614e-23],
       [3.3527245e-23, 1.4266392e-26, 9.7643908e-32, ..., 3.7197943e-27,
        7.2161421e-25, 5.1433125e-25]], dtype=float32)

In [ ]:
# pred_bin = predictions.round().astype(np.int32)
# pred_bin

In [ ]:
importlib.reload(SLR_model)

<module 'SLR_model' from '/home/shd/BomNae-SLR/SLR_model.py'>

In [ ]:
SLR_model.decode_onehot2d(predictions)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1935, 1935, 1891, 1891, 1891, 1935, 1891, 1891, 1935])>

In [ ]:
SLR_model.bin2num([1,0,1,1,1,0,1,1,1,0,1,0])

AttributeError: module 'SLR_model' has no attribute 'bin2num'

In [20]:
model.predict

<bound method TensorFlowTrainer.predict of <SLRModel name=slr_model_1, built=True>>